name: Project Construction

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create-folder:
    name: create-folder
    runs-on: self-hosted
    steps:
      - name: Create folder on the local WSL2 environment
        run: rm -rf ~/springboot_cicd_demo && mkdir -p ~/springboot_cicd_demo

  build:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml

      - name: Rename jar
        run: mv target/*.jar target/app.jar

      - name: copy file via ssh password
        needs: create-folder
        run: |
          echo "Copying files to local folder..."
          cp target/app.jar ~/springboot_cicd_demo/


