name: Project Construction

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create-folder:
    name: Create Folder
    runs-on: self-hosted
    steps:
      - name: Create folder on the local WSL2 environment
        run: rm -rf ~/spring_boot_cicd_demo && mkdir -p ~/spring_boot_cicd_demo

  build:
    name: Build Project
    runs-on: self-hosted
    needs: create-folder
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml

      - name: Rename jar
        run: mv target/*.jar target/app.jar

      - name: copy file via ssh password
        run: |
          echo "Copying files to local folder..."
          cp target/app.jar ~/spring_boot_cicd_demo/

  run-jar:
      name: Run App
      runs-on: self-hosted
      needs: build
      steps:
        - name: run the app
          run: |
            echo "Creating a symbolic link to the app.jar..."
            echo ${{ secrets.PASSWORD }} | sudo -S ln -sf ~/spring_boot_cicd_demo/app.jar /etc/init.d/app
            echo "Starting the service..."
            echo ${{ secrets.PASSWORD }} | /etc/init.d/app start