name: Project Construction

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  create-folder:
    name: create-folder
    runs-on: self-hosted
    steps:
      - name: Create folder on the local WSL2 environment
        run: rm -rf ~/springboot_cicd_demo && mkdir -p ~/springboot_cicd_demo

  build:
    name: Build Project
    runs-on: self-hosted
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        run: |
          curl -sL https://archive.apache.org/dist/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz | tar xz -C /opt
          sudo ln -s /opt/apache-maven-3.9.5/bin/mvn /usr/local/bin/mvn

      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml
